project:
  name: dopamine-starter-mvc
  version: 0.0.0
  description: Spring Boot starter for shared infrastructure
  longDescription: |
    Spring Boot starter for shared infrastructure like response formatting, 
    trace ID management, i18n support, etc.
  authors:
    - DaeYong Kim
  license: MIT
  inceptionYear: 2025
  links:
    homepage: https://github.com/LiamKim-DaeYong/dopamine
    documentation: https://github.com/LiamKim-DaeYong/dopamine/blob/main/README.md
  languages:
    java:
      groupId: io.github.liamkim-daeyong
      version: 21

release:
  github:
    owner: LiamKim-DaeYong
    name: dopamine
    token: "{{envs.JRELEASER_GITHUB_TOKEN}}"
    tagName: "v{{projectVersion}}"
    releaseName: "dopamine-starter-mvc v{{projectVersion}} (preview)"
    overwrite: true
    changelog:
      preset: conventional-commits
      formatted: ALWAYS
    milestone:
      close: false

signing:
  active: ALWAYS
  armored: true
  mode: FILE
  publicKey: "{{envs.SIGNING_PUBLIC_KEY}}"
  secretKey: "{{envs.SIGNING_KEY}}"
  passphrase: "{{envs.SIGNING_KEY_PASSPHRASE}}"

deploy:
  maven:
    mavenCentral:
      sonatype:
        active: ALWAYS
        url: https://central.sonatype.com/api/v1/publisher
        username: "{{envs.CENTRAL_PORTAL_USERNAME}}"
        password: "{{envs.CENTRAL_PORTAL_PASSWORD}}"
        stagingRepositories:
          - build/jreleaser/staging

distributions:
  dopamine-starter-mvc:
    type: JAVA_BINARY
    artifacts:
      - path: build/libs/dopamine-starter-mvc-{{projectVersion}}.jar
