project:
  name: dopamine-starter-mvc
  version: "${PROJECT_VERSION}"
  description: Spring Boot starter for shared infrastructure
  longDescription: |
    Spring Boot starter for shared infrastructure like response formatting, 
    trace ID management, i18n support, etc.
  authors:
    - DaeYong Kim
  license: MIT
  inceptionYear: 2025
  links:
    homepage: https://github.com/LiamKim-DaeYong/dopamine
    documentation: https://github.com/LiamKim-DaeYong/dopamine/blob/main/README.md
  languages:
    java:
      groupId: io.github.liamkim-daeyong
      version: 21

release:
  github:
    owner: LiamKim-DaeYong
    name: dopamine
    token: "${JRELEASER_GITHUB_TOKEN}"
    tagName: "v${PROJECT_VERSION}"
    releaseName: "dopamine-starter-mvc v${PROJECT_VERSION} (preview)"
    overwrite: true
    changelog:
      preset: conventional-commits
      formatted: ALWAYS
    milestone:
      close: false

signing:
  active: ALWAYS
  armored: true
  mode: COMMAND
  passphrase: "${SIGNING_KEY_PASSPHRASE}"

deploy:
  maven:
    mavenCentral:
      sonatype:
        active: ALWAYS
        url: https://central.sonatype.com/api/v1/publisher
        username: "${CENTRAL_PORTAL_USERNAME}"
        password: "${CENTRAL_PORTAL_PASSWORD}"
        stagingRepositories:
          - ./build/repos/releases

distributions:
  dopamine-starter-mvc:
    type: JAVA_BINARY
    artifacts:
      - path: modules/starter/dopamine-starter-mvc/build/libs/dopamine-starter-mvc-${PROJECT_VERSION}.jar
