project:
  name: dopamine-starter-mvc
  version: 0.1.0
  description: Spring Boot starter for shared infrastructure like response, traceId, i18n, etc.
  authors: [DaeYong Kim]
  license: MIT
  inceptionYear: 2025

signing:
  enabled: true
  active: ALWAYS
  mode: COMMAND
  command:
    executable: gpg
    keyName: env:SIGNING_KEY_ID
    passphrase: env:SIGNING_KEY_PASSPHRASE

deploy:
  enabled: true
  maven:
    central:
      active: ALWAYS
      groupId: io.github.liamkim-daeyong
      artifactId: dopamine-starter-mvc
      credentials:
        username: env:CENTRAL_PORTAL_USERNAME
        password: env:CENTRAL_PORTAL_PASSWORD

release:
  github:
    active: ALWAYS
    token: env:JRELEASER_GITHUB_TOKEN
    overwrite: true
    tagName: v{{projectVersion}}
    releaseName: dopamine-starter-mvc v{{projectVersion}} (preview)
    changelog:
      formatted: ALWAYS
      preset: conventional-commits
