[versions]
kotlin = "1.9.25"
spring-boot = "3.4.5"
spring-dependency-management = "1.1.7"
kotest = "5.8.1"
kotest-extensions-spring = "1.3.0"
ktlint-plugin = "12.2.0"
ktlint-cli = "1.2.1"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-plugin" }

[libraries]
spring-boot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure" }
spring-boot-starter-web = { group = "org.springframework.boot", name = "spring-boot-starter-web" }
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
assertj-core = { module = "org.assertj:assertj-core" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind" }

kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-extensions-spring = { module = "io.kotest.extensions:kotest-extensions-spring", version.ref = "kotest-extensions-spring" }

# Test libraries
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test" }
