package io.dopamine.docs.config

import org.springframework.boot.context.properties.ConfigurationProperties

/**
 * Configuration properties for Dopamine docs behavior.
 * Bound to the "dopamine.docs" prefix in application settings.
 */
@ConfigurationProperties(DocsPropertyKeys.PREFIX)
data class DocsProperties(
    /**
     * Whether to enable the Dopamine docs module.
     */
    val enabled: Boolean = true,
    /**
     * Settings for Swagger/OpenAPI documentation.
     */
    val swagger: Swagger = Swagger(),
    /**
     * Settings for serving static Markdown or HTML documentation.
     */
    val static: Static = Static(),
    /**
     * Settings for admin-facing documentation UI (e.g., embedded viewer).
     */
    val admin: Admin = Admin(),
) {
    /**
     * Swagger/OpenAPI documentation settings.
     */
    data class Swagger(
        /**
         * Whether to enable Swagger UI and OpenAPI documentation.
         */
        val enabled: Boolean = true,
        /**
         * The title displayed in Swagger UI.
         */
        val title: String = "Dopamine API",
        /**
         * Version string displayed in Swagger UI and OpenAPI spec.
         */
        val version: String = "v1.0.0",
        /**
         * Short description shown in the API documentation.
         */
        val description: String = "API documentation generated by Dopamine",
        /**
         * Additional Swagger documentation groups defined by the user.
         */
        val additionalGroups: List<Group> = emptyList(),
    ) {
        data class Group(
            val name: String,
            val basePackages: List<String>,
        )
    }

    /**
     * Static Markdown/HTML documentation settings.
     */
    data class Static(
        /**
         * Whether to enable serving static documentation.
         */
        val enabled: Boolean = true,
        /**
         * Resource path for loading static documentation files.
         * Can be a classpath (e.g., classpath:/docs) or an absolute file path.
         */
        val path: String = "classpath:/docs",
    )

    /**
     * Admin UI for showing documentation within an internal dashboard.
     */
    data class Admin(
        /**
         * Whether to enable admin documentation UI.
         */
        val enabled: Boolean = false,
    )
}
