name: Release with JReleaser

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Verify Java version
        run: java -version

      - name: Debug PGP Key
        run: |
          echo "$SIGNING_KEY" | head -n 5

      - name: Set up GPG key
        run: |
          printf "%s\n" "$SIGNING_KEY" | gpg --batch --import
          printf "%s\n" "$SIGNING_PUBLIC_KEY" | gpg --batch --import

      - name: Build and publish with JReleaser
        uses: jreleaser/release-action@v2
        with:
          version: 1.19.0
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PUBLIC_KEY: ${{ secrets.SIGNING_PUBLIC_KEY }}
          SIGNING_KEY_PASSPHRASE: ${{ secrets.SIGNING_KEY_PASSPHRASE }}
          CENTRAL_PORTAL_USERNAME: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
          CENTRAL_PORTAL_PASSWORD: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}
