name: Release with JReleaser

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Verify Java version
        run: java -version

      - name: Decode and import GPG private key
        continue-on-error: true
        run: |
          printf "%s" "$SIGNING_KEY" | base64 --decode > private.asc
          gpg --batch --import private.asc

      - name: DEBUG base64 decode preview
        run: |
          echo "[Decoded preview]"
          printf "%s" "$SIGNING_KEY" | base64 --decode | head -n 10 || echo "[Decode failed]"
          echo "[End preview]"

      - name: DEBUG decoded length
        run: |
          echo "[Decoded length]"
          printf "%s" "$SIGNING_KEY" | base64 --decode | wc -c || echo "[Decode length failed]"

      - name: Decode and import GPG public key
        run: |
          printf "%s" "$SIGNING_PUBLIC_KEY" | base64 --decode > public.asc
          gpg --batch --import public.asc

      - name: Build and publish with JReleaser
        uses: jreleaser/release-action@v2
        with:
          version: 1.19.0
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PUBLIC_KEY: ${{ secrets.SIGNING_PUBLIC_KEY }}
          SIGNING_KEY_PASSPHRASE: ${{ secrets.SIGNING_KEY_PASSPHRASE }}
          CENTRAL_PORTAL_USERNAME: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
          CENTRAL_PORTAL_PASSWORD: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}
