name: Release with JReleaser

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      SIGNING_PUBLIC_KEY: ${{ secrets.SIGNING_PUBLIC_KEY }}
      SIGNING_KEY_PASSPHRASE: ${{ secrets.SIGNING_KEY_PASSPHRASE }}
      CENTRAL_PORTAL_USERNAME: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
      CENTRAL_PORTAL_PASSWORD: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}
      JRELEASER_GITHUB_TOKEN: ${{ secrets.JRELEASER_GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Verify Java version
        run: java -version

      - name: Install expect
        run: sudo apt-get update && sudo apt-get install -y expect

      - name: Decode and import GPG private key
        run: |
          printf "%s" "$SIGNING_KEY" | base64 --decode > private.asc
          gpg --batch --import private.asc

      - name: Decode and import GPG public key
        run: |
          printf "%s" "$SIGNING_PUBLIC_KEY" | base64 --decode > public.asc
          gpg --batch --import public.asc

      - name: Trust imported GPG key using expect
        run: |
          KEY_ID=$(gpg --list-keys --with-colons | awk -F: '/^pub/ { print $5; exit }')
          echo "Setting trust level 5 for $KEY_ID"
          expect <<EOF
            spawn gpg --command-fd 0 --status-fd 1 --edit-key $KEY_ID trust
            send "5\n"
            send "y\n"
            send "save\n"
            expect eof
          EOF

      - name: Show imported secret keys
        run: gpg --list-secret-keys --keyid-format LONG

      - name: Show all imported keys
        run: gpg --list-keys --keyid-format LONG

      - name: Set project version from tag (strip leading 'v')
        run: echo "PROJECT_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Generate JReleaser config with injected version
        run: |
          sudo apt-get install -y gettext
          envsubst < .jreleaser.yml > .jreleaser.generated.yml

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build JAR
        run: ./gradlew clean build -x test

      - name: Build and publish with JReleaser
        uses: jreleaser/release-action@v2
        with:
          version: 1.19.0
          arguments: full-release --config-file=.jreleaser.generated.yml
