name: Release with JReleaser

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      SIGNING_PUBLIC_KEY: ${{ secrets.SIGNING_PUBLIC_KEY }}
      SIGNING_KEY_PASSPHRASE: ${{ secrets.SIGNING_KEY_PASSPHRASE }}
      CENTRAL_PORTAL_USERNAME: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
      CENTRAL_PORTAL_PASSWORD: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}
      JRELEASER_GITHUB_TOKEN: ${{ secrets.JRELEASER_GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext

      - name: Setup GPG environment
        run: |
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg
          echo "use-agent" >> ~/.gnupg/gpg.conf
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          gpgconf --kill gpg-agent

      - name: Import GPG private key (ASCII-armored)
        run: |
          echo "$SIGNING_KEY" > private.asc
          gpg --batch --yes --import private.asc

      - name: Warm up GPG keyring
        run: gpg --list-secret-keys || true

      - name: Set project version from tag (strip leading 'v')
        run: echo "PROJECT_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Generate JReleaser config with injected version
        run: envsubst < .jreleaser.yml > .jreleaser.generated.yml

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Publish to local releases repo
        run: ./gradlew publishAllPublicationsToReleasesRepository

      - name: Build and publish with JReleaser
        uses: jreleaser/release-action@v2
        with:
          version: 1.19.0
          arguments: full-release --config-file=.jreleaser.generated.yml
