name: Release to Maven Central

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_KEY_PASSPHRASE }}
      OSSRH_USERNAME: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant permission to gradlew
        run: chmod +x ./gradlew

      - name: Inject signing and publishing credentials
        run: |
          echo "signingKey=${SIGNING_KEY}" >> gradle.properties
          echo "signingPassword=${SIGNING_PASSWORD}" >> gradle.properties
          echo "ossrhUsername=${OSSRH_USERNAME}" >> gradle.properties
          echo "ossrhPassword=${OSSRH_PASSWORD}" >> gradle.properties

      - name: Build and publish to Maven Central
        run: ./gradlew publish
