name: Release with JReleaser

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      SIGNING_PUBLIC_KEY: ${{ secrets.SIGNING_PUBLIC_KEY }}
      SIGNING_KEY_PASSPHRASE: ${{ secrets.SIGNING_KEY_PASSPHRASE }}
      CENTRAL_PORTAL_USERNAME: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
      CENTRAL_PORTAL_PASSWORD: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}
      JRELEASER_GITHUB_TOKEN: ${{ secrets.JRELEASER_GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Verify Java version
        run: java -version

      - name: Decode and import GPG private key
        run: |
          printf "%s" "$SIGNING_KEY" | base64 --decode > private.asc
          gpg --batch --import private.asc

      - name: Decode and import GPG public key
        run: |
          printf "%s" "$SIGNING_PUBLIC_KEY" | base64 --decode > public.asc
          gpg --batch --import public.asc

      - name: Set project version from tag (strip leading 'v')
        run: echo "JRELEASER_PROJECT_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Build and publish with JReleaser
        uses: jreleaser/release-action@v2
        with:
          version: 1.19.0
          arguments: full-release --set-property=projectVersion=${{ env.JRELEASER_PROJECT_VERSION }} --config-file=.jreleaser.yml