name: Release to Maven Central

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      JRELEASER_GITHUB_TOKEN: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
      JRELEASER_SIGNING_KEY: ${{ secrets.JRELEASER_SIGNING_KEY }}
      JRELEASER_SIGNING_PUBLIC_KEY: ${{ secrets.JRELEASER_SIGNING_PUBLIC_KEY }}
      JRELEASER_SIGNING_PASSPHRASE: ${{ secrets.JRELEASER_SIGNING_PASSPHRASE }}
      JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
      JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.JRELEASER_MAVENCENTRAL_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant permission to gradlew
        run: chmod +x ./gradlew

      - name: Inject signing and publishing credentials
        run: |
          echo "JRELEASER_GITHUB_TOKEN=${JRELEASER_GITHUB_TOKEN}" >> gradle.properties
          echo "JRELEASER_SIGNING_KEY=${JRELEASER_SIGNING_KEY}" >> gradle.properties
          echo "JRELEASER_SIGNING_PUBLIC_KEY=${JRELEASER_SIGNING_PUBLIC_KEY}" >> gradle.properties
          echo "JRELEASER_SIGNING_PASSPHRASE=${JRELEASER_SIGNING_PASSPHRASE}" >> gradle.properties
          echo "JRELEASER_MAVENCENTRAL_USERNAME=${JRELEASER_MAVENCENTRAL_USERNAME}" >> gradle.properties
          echo "JRELEASER_MAVENCENTRAL_PASSWORD=${JRELEASER_MAVENCENTRAL_PASSWORD}" >> gradle.properties

      - name: Build all artifacts
        run: ./gradlew build

      - name: Release with JReleaser (run from root project)
        run: ./gradlew jreleaserFullRelease