name: Release to Maven Central

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      SIGNING_PUBLIC_KEY: ${{ secrets.SIGNING_PUBLIC_KEY }}
      SIGNING_KEY_PASSPHRASE: ${{ secrets.SIGNING_KEY_PASSPHRASE }}
      CENTRAL_PORTAL_USERNAME: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
      CENTRAL_PORTAL_PASSWORD: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant permission to gradlew
        run: chmod +x ./gradlew

      - name: Inject signing and publishing credentials
        run: |
          echo "signingKey=${SIGNING_KEY}" >> gradle.properties
          echo "signingPublicKey=${SIGNING_PUBLIC_KEY}" >> gradle.properties
          echo "signingKeyPassphrase=${SIGNING_KEY_PASSPHRASE}" >> gradle.properties
          echo "centralPortalUsername=${CENTRAL_PORTAL_USERNAME}" >> gradle.properties
          echo "centralPortalPassword=${CENTRAL_PORTAL_PASSWORD}" >> gradle.properties

      - name: Build and publish to Maven Central
        run: ./gradlew publish jreleaserFullRelease
